### ISSUE TITLE
Load all experiments from DHS and wg* files

### ISSUE THREAD

**Issue by oddodaoddo** [databio/episb-provider#33]

**Comment by oddodaoddo** [comment]
Right now we are limited by the space on the machine this is running on. I am closing this ticket since I have a script to automate the loading all the experiments if need be.

**Comment by oddodaoddo** [comment]
I think we are OK for now - NFS will not work for elastic - we can re-visit when the time comes to put elastic into production. Sounds good? :smile:

**Comment by nmagee** [comment]
Sounds fine. Plus I can always grab one of the 8TB drives from the storage nodes and throw it into this instance. Not being an Elastic guy, is local storage always a requirement for any decent performance? If so, I may redesign things a little bit for DCOS, and make a dedicated node for Elastic containers.

**Comment by oddodaoddo** [comment]
So many ways to skin the cat :). I think NFS is almost never a good choice :smiley:
