### ISSUE TITLE
dockerizing episb-provider

### ISSUE THREAD

**Issue by nsheff** [databio/episb-provider#4]
It looks like this is already set up to run in `docker`, but is this runnable locally within a container? If so, can we add instructions for how to run the provider container?

Related to https://github.com/databio/episb-hub/issues/2

**Comment by nsheff** [comment]
I can't build it: 

```
nsheff@puma:~/code/episb-provider/episb-provider$ docker build -t episb-provider .
Sending build context to Docker daemon  73.22kB
Step 1/4 : FROM tomcat:8.5
 ---> dd6ff929584a
Step 2/4 : RUN rm -rf /usr/local/tomcat/webapps/*
 ---> Using cache
 ---> 1304a958f826
Step 3/4 : COPY target/scala-2.12/episb-provider_2.12-0.4.0.war /usr/local/tomcat/webapps/episb-provider.war
lstat target/scala-2.12/episb-provider_2.12-0.4.0.war: no such file or directory
```

**Comment by nsheff** [comment]
there is no `target` folder in the repository.

**Comment by oddodaoddo** [comment]
Ok - I noticed that the Dockerfile had not been updated in master branch to track the version built - I updated the file now.

**Comment by nsheff** [comment]
I was using the dev branch. we should avoid changing the master branch outside of new releases
